version: '3.9'


services:
  chromadb:
    image: chromadb/chroma:0.5.13
    volumes:
      - ./chromadb:/chromadb/data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=./chroma/data
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    
  
  # data_loader:
  #   build:
  #     context: ./
  #     dockerfile: ./core/Dockerfile
  #   depends_on:
  #     chromadb:
  #       condition: service_healthy

  # server:
  #   build:
  #     context: ./
  #     dockerfile: ./server/Dockerfile
  #   depends_on: 
  #     data_loader:
  #       condition: service_completed_successfully
  #     chromadb:
  #       condition: service_healthy
    
